FROM prefecthq/prefect:2-python3.9
RUN pip install prefect-gcp "prefect-gcp[cloud_storage]" opendatasets kaggle pandas pandas_gbq
COPY kaggle.json /home/.kaggle/kaggle.json
RUN chmod 600 /home/.kaggle/kaggle.json